services:
  - type: web
    name: kurung-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_MOCK_DATA
        value: false
      - key: PORT
        value: 10000
      - key: PUPPETEER_HEADLESS
        value: true
      - key: PUPPETEER_TIMEOUT
        value: 30000 