services:
  - type: web
    name: kurung-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_MOCK_DATA
        value: "true"
      - key: PORT
        value: 10000 